version: 2
updates:
- package-ecosystem: npm
  directory: "/addon"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 4
- package-ecosystem: npm
  directory: "/test-app"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 3
